<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\CoAuthorInvitationController;
use App\Controllers\AccountController;
use App\Controllers\AdminScholarlyController;
use App\Controllers\HighlightController;
use App\Controllers\DashboardController;
use App\Controllers\FacultyDeadlineSettingsController;
use App\Controllers\DirectMessageController;
use App\Controllers\MonitoringController;
use App\Controllers\NotificationController;
use App\Controllers\ProjectController;
use App\Controllers\ProfileController;
use App\Controllers\ProposalController;
use App\Controllers\ScholarlyController;
use App\Middleware\AuthMiddleware;
use App\Middleware\RoleMiddleware;

$auth = [[AuthMiddleware::class, 'handle']];
$admin = [...$auth, RoleMiddleware::require('ride_admin')];

$router->get('/', [DashboardController::class, 'index'], $auth);
$router->get('/dashboard', [DashboardController::class, 'index'], $auth);
$router->get('/messages', [DashboardController::class, 'messages'], $auth);
$router->get('/messages/conversation/{partnerId}', [DirectMessageController::class, 'conversation'], $auth);
$router->post('/messages/send', [DirectMessageController::class, 'send'], $auth);
$router->post('/messages/update', [DashboardController::class, 'updateMessage'], $auth);
$router->post('/messages/announcements/{id}/update', [DashboardController::class, 'updateAnnouncement'], $auth);
$router->post('/messages/announcements/{id}/delete', [DashboardController::class, 'deleteAnnouncement'], $auth);
$router->get('/monitoring', [MonitoringController::class, 'index'], $auth);
$router->get('/settings/faculty-deadlines', [FacultyDeadlineSettingsController::class, 'index'], $auth);
$router->post('/settings/faculty-deadlines', [FacultyDeadlineSettingsController::class, 'update'], $auth);

$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/register', [AuthController::class, 'showRegister']);
$router->post('/register', [AuthController::class, 'register']);
$router->get('/logout', [AuthController::class, 'logout'], $auth);

$router->get('/profile', [ProfileController::class, 'index'], $auth);
$router->post('/profile/update', [ProfileController::class, 'update'], $auth);
$router->post('/profile/password', [ProfileController::class, 'updatePassword'], $auth);
$router->post('/profile/avatar', [ProfileController::class, 'uploadAvatar'], $auth);
$router->post('/profile/avatar/remove', [ProfileController::class, 'removeAvatar'], $auth);
$router->get('/avatars/{userId}', [ProfileController::class, 'showAvatar']);
$router->post('/profile/signature', [ProfileController::class, 'uploadSignature'], $auth);
$router->post('/profile/signature/remove', [ProfileController::class, 'removeSignature'], $auth);
$router->get('/signatures/{userId}', [ProfileController::class, 'showSignature'], $auth);

$router->get('/proposals', [ProposalController::class, 'index'], $auth);
$router->get('/proposals/terminal-report-registry', [ProposalController::class, 'terminalReportRegistry'], $auth);
$router->get('/proposals/create', [ProposalController::class, 'create'], $auth);
$router->get('/proposals/create/manuscript', [ProposalController::class, 'createManuscript'], $auth);
$router->get('/proposals/create/completed-researches', [ProposalController::class, 'createCompletedResearches'], $auth);
$router->get('/proposals/create/ongoing-researches', [ProposalController::class, 'createOngoingResearches'], $auth);
$router->get('/proposals/create/research-output-published', [ProposalController::class, 'createResearchOutputPublished'], $auth);
$router->get('/proposals/create/research-output-presented', [ProposalController::class, 'createResearchOutputPresented'], $auth);
$router->get('/proposals/create/commercialized', [ProposalController::class, 'createCommercialized'], $auth);
$router->get('/proposals/create/resulted-in-extension', [ProposalController::class, 'createResultedInExtension'], $auth);
$router->get('/proposals/create/journal-citation', [ProposalController::class, 'createJournalCitation'], $auth);
$router->get('/proposals/create/book-citation', [ProposalController::class, 'createBookCitation'], $auth);
$router->get('/proposals/create/inventions-um-copyrights', [ProposalController::class, 'createInventionsUmCopyrights'], $auth);
$router->get('/proposals/create/linkages', [ProposalController::class, 'createLinkages'], $auth);
$router->get('/proposals/create/consolidated-completed-researches', [ProposalController::class, 'createConsolidatedCompletedResearches'], $auth);
$router->get('/proposals/create/consolidated-ongoing-researches', [ProposalController::class, 'createConsolidatedOngoingResearches'], $auth);
$router->get('/proposals/create/consolidated-research-output-published', [ProposalController::class, 'createConsolidatedResearchOutputPublished'], $auth);
$router->get('/proposals/create/consolidated-research-output-presented', [ProposalController::class, 'createConsolidatedResearchOutputPresented'], $auth);
$router->get('/proposals/create/consolidated-commercialized', [ProposalController::class, 'createConsolidatedCommercialized'], $auth);
$router->get('/proposals/create/consolidated-resulted-in-extension', [ProposalController::class, 'createConsolidatedResultedInExtension'], $auth);
$router->get('/proposals/create/consolidated-journal-citation', [ProposalController::class, 'createConsolidatedJournalCitation'], $auth);
$router->get('/proposals/create/consolidated-book-citation', [ProposalController::class, 'createConsolidatedBookCitation'], $auth);
$router->get('/proposals/create/consolidated-inventions-um-copyrights', [ProposalController::class, 'createConsolidatedInventionsUmCopyrights'], $auth);
$router->get('/proposals/create/consolidated-linkages', [ProposalController::class, 'createConsolidatedLinkages'], $auth);
$router->get('/proposals/create/progress-report', [ProposalController::class, 'createProgressReport'], $auth);
$router->get('/proposals/create/terminal-report', [ProposalController::class, 'createTerminalReport'], $auth);
$router->get('/proposals/create/terminal-report-assessment-form', [ProposalController::class, 'createTerminalReportAssessmentForm'], $auth);
$router->get('/proposals/create/obr-matrix', [ProposalController::class, 'createObrMatrix'], $auth);
$router->get('/proposals/create/trainings-conducted', [ProposalController::class, 'createTrainingsConducted'], $auth);
$router->get('/proposals/create/technical-advisory', [ProposalController::class, 'createTechnicalAdvisory'], $auth);
$router->get('/proposals/create/extension-linkages', [ProposalController::class, 'createExtensionLinkages'], $auth);
$router->get('/proposals/create/outreach-activities', [ProposalController::class, 'createOutreachActivities'], $auth);
$router->get('/proposals/create/technology-adoption', [ProposalController::class, 'createTechnologyAdoption'], $auth);
$router->get('/proposals/create/required-files', [ProposalController::class, 'createRequiredFiles'], $auth);
$router->post('/proposals/manuscript', [ProposalController::class, 'storeManuscript'], $auth);
$router->post('/proposals/completed-researches', [ProposalController::class, 'storeCompletedResearches'], $auth);
$router->post('/proposals/ongoing-researches', [ProposalController::class, 'storeOngoingResearches'], $auth);
$router->post('/proposals/research-output-published', [ProposalController::class, 'storeResearchOutputPublished'], $auth);
$router->post('/proposals/research-output-presented', [ProposalController::class, 'storeResearchOutputPresented'], $auth);
$router->post('/proposals/commercialized', [ProposalController::class, 'storeCommercialized'], $auth);
$router->post('/proposals/resulted-in-extension', [ProposalController::class, 'storeResultedInExtension'], $auth);
$router->post('/proposals/journal-citation', [ProposalController::class, 'storeJournalCitation'], $auth);
$router->post('/proposals/book-citation', [ProposalController::class, 'storeBookCitation'], $auth);
$router->post('/proposals/inventions-um-copyrights', [ProposalController::class, 'storeInventionsUmCopyrights'], $auth);
$router->post('/proposals/linkages', [ProposalController::class, 'storeLinkages'], $auth);
$router->post('/proposals/consolidated-completed-researches', [ProposalController::class, 'storeConsolidatedCompletedResearches'], $auth);
$router->post('/proposals/consolidated-ongoing-researches', [ProposalController::class, 'storeConsolidatedOngoingResearches'], $auth);
$router->post('/proposals/consolidated-research-output-published', [ProposalController::class, 'storeConsolidatedResearchOutputPublished'], $auth);
$router->post('/proposals/consolidated-research-output-presented', [ProposalController::class, 'storeConsolidatedResearchOutputPresented'], $auth);
$router->post('/proposals/consolidated-commercialized', [ProposalController::class, 'storeConsolidatedCommercialized'], $auth);
$router->post('/proposals/consolidated-resulted-in-extension', [ProposalController::class, 'storeConsolidatedResultedInExtension'], $auth);
$router->post('/proposals/consolidated-journal-citation', [ProposalController::class, 'storeConsolidatedJournalCitation'], $auth);
$router->post('/proposals/consolidated-book-citation', [ProposalController::class, 'storeConsolidatedBookCitation'], $auth);
$router->post('/proposals/consolidated-inventions-um-copyrights', [ProposalController::class, 'storeConsolidatedInventionsUmCopyrights'], $auth);
$router->post('/proposals/consolidated-linkages', [ProposalController::class, 'storeConsolidatedLinkages'], $auth);
$router->post('/proposals/progress-report', [ProposalController::class, 'storeProgressReport'], $auth);
$router->post('/proposals/terminal-report', [ProposalController::class, 'storeTerminalReport'], $auth);
$router->post('/proposals/terminal-report-assessment-form', [ProposalController::class, 'storeTerminalReportAssessmentForm'], $auth);
$router->post('/proposals/obr-matrix', [ProposalController::class, 'storeObrMatrix'], $auth);
$router->post('/proposals/trainings-conducted', [ProposalController::class, 'storeTrainingsConducted'], $auth);
$router->post('/proposals/technical-advisory', [ProposalController::class, 'storeTechnicalAdvisory'], $auth);
$router->post('/proposals/extension-linkages', [ProposalController::class, 'storeExtensionLinkages'], $auth);
$router->post('/proposals/outreach-activities', [ProposalController::class, 'storeOutreachActivities'], $auth);
$router->post('/proposals/technology-adoption', [ProposalController::class, 'storeTechnologyAdoption'], $auth);
$router->post('/proposals', [ProposalController::class, 'store'], $auth);
$router->get('/proposals/{id}', [ProposalController::class, 'show'], $auth);
$router->get('/proposals/{id}/edit', [ProposalController::class, 'edit'], $auth);
$router->get('/proposals/{id}/edit/required-files', [ProposalController::class, 'editRequiredFiles'], $auth);
$router->post('/proposals/{id}/required-files', [ProposalController::class, 'updateRequiredFiles'], $auth);
$router->post('/proposals/{id}/manuscript', [ProposalController::class, 'updateManuscript'], $auth);
$router->post('/proposals/{id}/completed-researches', [ProposalController::class, 'updateCompletedResearches'], $auth);
$router->post('/proposals/{id}/ongoing-researches', [ProposalController::class, 'updateOngoingResearches'], $auth);
$router->post('/proposals/{id}/research-output-published', [ProposalController::class, 'updateResearchOutputPublished'], $auth);
$router->post('/proposals/{id}/research-output-presented', [ProposalController::class, 'updateResearchOutputPresented'], $auth);
$router->post('/proposals/{id}/commercialized', [ProposalController::class, 'updateCommercialized'], $auth);
$router->post('/proposals/{id}/resulted-in-extension', [ProposalController::class, 'updateResultedInExtension'], $auth);
$router->post('/proposals/{id}/journal-citation', [ProposalController::class, 'updateJournalCitation'], $auth);
$router->post('/proposals/{id}/book-citation', [ProposalController::class, 'updateBookCitation'], $auth);
$router->post('/proposals/{id}/inventions-um-copyrights', [ProposalController::class, 'updateInventionsUmCopyrights'], $auth);
$router->post('/proposals/{id}/linkages', [ProposalController::class, 'updateLinkages'], $auth);
$router->post('/proposals/{id}/consolidated-completed-researches', [ProposalController::class, 'updateConsolidatedCompletedResearches'], $auth);
$router->post('/proposals/{id}/consolidated-ongoing-researches', [ProposalController::class, 'updateConsolidatedOngoingResearches'], $auth);
$router->post('/proposals/{id}/consolidated-research-output-published', [ProposalController::class, 'updateConsolidatedResearchOutputPublished'], $auth);
$router->post('/proposals/{id}/consolidated-research-output-presented', [ProposalController::class, 'updateConsolidatedResearchOutputPresented'], $auth);
$router->post('/proposals/{id}/consolidated-commercialized', [ProposalController::class, 'updateConsolidatedCommercialized'], $auth);
$router->post('/proposals/{id}/consolidated-resulted-in-extension', [ProposalController::class, 'updateConsolidatedResultedInExtension'], $auth);
$router->post('/proposals/{id}/consolidated-journal-citation', [ProposalController::class, 'updateConsolidatedJournalCitation'], $auth);
$router->post('/proposals/{id}/consolidated-book-citation', [ProposalController::class, 'updateConsolidatedBookCitation'], $auth);
$router->post('/proposals/{id}/consolidated-inventions-um-copyrights', [ProposalController::class, 'updateConsolidatedInventionsUmCopyrights'], $auth);
$router->post('/proposals/{id}/consolidated-linkages', [ProposalController::class, 'updateConsolidatedLinkages'], $auth);
$router->post('/proposals/{id}/progress-report', [ProposalController::class, 'updateProgressReport'], $auth);
$router->post('/proposals/{id}/terminal-report', [ProposalController::class, 'updateTerminalReport'], $auth);
$router->post('/proposals/{id}/terminal-report-assessment-form', [ProposalController::class, 'updateTerminalReportAssessmentForm'], $auth);
$router->post('/proposals/{id}/obr-matrix', [ProposalController::class, 'updateObrMatrix'], $auth);
$router->post('/proposals/{id}/trainings-conducted', [ProposalController::class, 'updateTrainingsConducted'], $auth);
$router->post('/proposals/{id}/technical-advisory', [ProposalController::class, 'updateTechnicalAdvisory'], $auth);
$router->post('/proposals/{id}/extension-linkages', [ProposalController::class, 'updateExtensionLinkages'], $auth);
$router->post('/proposals/{id}/outreach-activities', [ProposalController::class, 'updateOutreachActivities'], $auth);
$router->post('/proposals/{id}/technology-adoption', [ProposalController::class, 'updateTechnologyAdoption'], $auth);
$router->post('/proposals/{id}/update', [ProposalController::class, 'update'], $auth);
$router->post('/proposals/{id}/submit', [ProposalController::class, 'submit'], $auth);
$router->post('/proposals/{id}/delete', [ProposalController::class, 'destroy'], $auth);
$router->post('/proposals/{id}/force-reopen', [ProposalController::class, 'forceReopen'], $auth);
$router->post('/proposals/{id}/force-delete', [ProposalController::class, 'forceDestroy'], $auth);
$router->post('/proposals/{id}/approve', [ProposalController::class, 'approve'], $auth);
$router->post('/proposals/{id}/return', [ProposalController::class, 'returnForRevision'], $auth);

$router->get('/projects', [ProjectController::class, 'index'], $auth);
$router->get('/projects/{id}', [ProjectController::class, 'show'], $auth);
$router->post('/projects/{id}/complete', [ProjectController::class, 'complete'], $auth);
$router->post('/projects/{id}/milestones', [ProjectController::class, 'storeMilestone'], $auth);
$router->post('/projects/{id}/milestones/{milestoneId}/complete', [ProjectController::class, 'completeMilestone'], $auth);
$router->get('/projects/{id}/reports/create', [ProjectController::class, 'createReport'], $auth);
$router->post('/projects/{id}/reports', [ProjectController::class, 'storeReport'], $auth);
$router->get('/projects/{id}/reports/{reportId}', [ProjectController::class, 'showReport'], $auth);
$router->post('/projects/{id}/reports/{reportId}', [ProjectController::class, 'updateReport'], $auth);
$router->post('/projects/{id}/reports/{reportId}/submit', [ProjectController::class, 'submitReport'], $auth);
$router->post('/projects/{id}/documents', [ProjectController::class, 'uploadDocument'], $auth);
$router->get('/projects/{id}/documents/{docId}', [ProjectController::class, 'downloadDocument'], $auth);
$router->post('/projects/{id}/documents/{docId}/delete', [ProjectController::class, 'deleteDocument'], $auth);
$router->post('/projects/{id}/innovation', [ProjectController::class, 'storeInnovation'], $auth);
$router->post('/projects/{id}/extension', [ProjectController::class, 'storeExtension'], $auth);
$router->get('/reports/extension-beneficiaries', [ProjectController::class, 'accreditationReport'], $auth);

$router->get('/notifications/{id}/read', [NotificationController::class, 'markRead'], $auth);

$router->get('/coauthor-invitations/{id}', [CoAuthorInvitationController::class, 'show'], $auth);
$router->post('/coauthor-invitations/{id}/accept', [CoAuthorInvitationController::class, 'accept'], $auth);
$router->post('/coauthor-invitations/{id}/reject', [CoAuthorInvitationController::class, 'reject'], $auth);

$router->get('/scholarly', [ScholarlyController::class, 'index'], $auth);
$router->post('/scholarly/papers', [ScholarlyController::class, 'storePaper'], $auth);
$router->post('/scholarly/presentations', [ScholarlyController::class, 'storePresentation'], $auth);
$router->post('/scholarly/papers/{id}/attachments', [ScholarlyController::class, 'uploadPaperAttachments'], $auth);
$router->post('/scholarly/presentations/{id}/attachments', [ScholarlyController::class, 'uploadPresentationAttachments'], $auth);
$router->get('/scholarly/attachments/{id}', [ScholarlyController::class, 'downloadAttachment'], $auth);
$router->post('/scholarly/attachments/{id}/delete', [ScholarlyController::class, 'destroyAttachment'], $auth);
$router->post('/scholarly/papers/{id}/delete', [ScholarlyController::class, 'destroyPaper'], $auth);
$router->post('/scholarly/presentations/{id}/delete', [ScholarlyController::class, 'destroyPresentation'], $auth);

$router->get('/admin/accounts', [AccountController::class, 'index'], $admin);
$router->post('/admin/accounts', [AccountController::class, 'store'], $admin);
$router->post('/admin/accounts/colleges', [AccountController::class, 'storeCollege'], $admin);
$router->post('/admin/accounts/colleges/default-centers', [AccountController::class, 'addDefaultCenters'], $admin);
$router->get('/admin/accounts/colleges/{id}/edit', [AccountController::class, 'editCollege'], $admin);
$router->post('/admin/accounts/colleges/{id}/update', [AccountController::class, 'updateCollege'], $admin);
$router->post('/admin/accounts/colleges/{id}/delete', [AccountController::class, 'destroyCollege'], $admin);
$router->get('/admin/accounts/{id}/edit', [AccountController::class, 'edit'], $admin);
$router->post('/admin/accounts/{id}/update', [AccountController::class, 'update'], $admin);
$router->post('/admin/accounts/{id}/reset-password', [AccountController::class, 'resetPassword'], $admin);
$router->post('/admin/accounts/{id}/delete', [AccountController::class, 'destroy'], $admin);
$router->post('/admin/accounts/{id}/restore', [AccountController::class, 'restore'], $admin);
$router->post('/admin/accounts/{id}/approve', [AccountController::class, 'approve'], $admin);
$router->post('/admin/accounts/{id}/reject', [AccountController::class, 'reject'], $admin);

$router->get('/admin/scholarly', [AdminScholarlyController::class, 'index'], $admin);
$router->post('/admin/scholarly/papers', [AdminScholarlyController::class, 'storePaper'], $admin);
$router->post('/admin/scholarly/presentations', [AdminScholarlyController::class, 'storePresentation'], $admin);
$router->get('/admin/scholarly/attachments/{id}', [AdminScholarlyController::class, 'downloadAttachment'], $admin);
$router->post('/admin/scholarly/papers/{id}/delete', [AdminScholarlyController::class, 'destroyPaper'], $admin);
$router->post('/admin/scholarly/presentations/{id}/delete', [AdminScholarlyController::class, 'destroyPresentation'], $admin);

$router->get('/admin/highlights', [HighlightController::class, 'index'], $admin);
$router->post('/admin/highlights/settings', [HighlightController::class, 'updateSettings'], $admin);
$router->post('/admin/highlights', [HighlightController::class, 'store'], $admin);
$router->post('/admin/highlights/{id}/update', [HighlightController::class, 'update'], $admin);
$router->post('/admin/highlights/{id}/move', [HighlightController::class, 'move'], $admin);
$router->post('/admin/highlights/{id}/delete', [HighlightController::class, 'destroy'], $admin);
