CREATE TABLE IF NOT EXISTS global_message_reads (
    user_id INT UNSIGNED PRIMARY KEY,
    last_read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
